force-app/main/default/objects/Account/fields/Applications_Or_Industries__c.field-meta.xml
<CustomField>
    <fullName>Applications_Or_Industries__c</fullName>
    <label>Applications Or Industries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value 1</fullName>
            </value>
            <value>
                <fullName>Value 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Types__c.field-meta.xml
<CustomField>
    <fullName>Customer_Types__c</fullName>
    <label>Customer Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1</fullName>
            </value>
            <value>
                <fullName>Type 2</fullName>
            </value>
            <value>
                <fullName>Type 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Literature_Codes__c.field-meta.xml
<CustomField>
    <fullName>Literature_Codes__c</fullName>
    <label>Literature Codes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code-1</fullName>
            </value>
            <value>
                <fullName>Code-2</fullName>
            </value>
            <value>
                <fullName>Code-3</fullName>
            </value>
            <value>
                <fullName>Code-4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market_Share__c.field-meta.xml
<CustomField>
    <fullName>Market_Share__c</fullName>
    <label>Market Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Product Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product 1</fullName>
            </value>
            <value>
                <fullName>Product 2</fullName>
            </value>
            <value>
                <fullName>Product 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Related_Industries__c.field-meta.xml
<CustomField>
    <fullName>Related_Industries__c</fullName>
    <label>Related Industries</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Apparel</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Biotechnology</fullName>
            </value>
            <value>
                <fullName>Chemicals</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Consulting</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Energy</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Environmental</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Food &amp; Beverage</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Machinery</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Recreation</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Trade_Fair_Invitation_Codes__c.field-meta.xml
<CustomField>
    <fullName>Trade_Fair_Invitation_Codes__c</fullName>
    <label>Trade Fair Invitation Codes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHelper.cls
public with sharing class OpportunityTriggerHelper {
    
    public static List<Account> getAccountList(Set<Id> mapAccIds){

     return                            [SELECT   Product_Interest__c,
                                                Literature_Codes__c,
                                                Trade_Fair_Invitation_Codes__c,
                                                Applications_Or_Industries__c,
                                                Related_Industries__c,
                                                AnnualRevenue,
                                                Market_Share__c,
                                                NumberOfEmployees,
                                                Customer_Types__c
                                       FROM     Account 
                                       WHERE    ID IN :mapAccIds];


    }
}